export const types = {
    RESET_AUTHOR_STATUS: 'RESET_AUTHOR_STATUS',

    SET_AUTHOR_LIST: 'SET_AUTHOR_LIST',
    SET_AUTHOR_LIST_STATUS: 'SET_AUTHOR_LIST_STATUS',

    SET_AUTHOR: 'SET_AUTHOR',
    SET_AUTHOR_STATUS: 'SET_AUTHOR_STATUS',

    CREATE_AUTHOR: 'CREATE_AUTHOR',
    CREATE_AUTHOR_STATUS: 'CREATE_AUTHOR_STATUS',

    EDIT_AUTHOR: 'EDIT_AUTHOR',
    EDIT_AUTHOR_STATUS: 'EDIT_AUTHOR_STATUS',

    DELETE_AUTHOR: 'DELETE_AUTHOR',
    DELETE_AUTHOR_STATUS: 'DELETE_AUTHOR_STATUS',
}