export const types = {
    SET_SONG_PAGE_BACKUP: 'SET_SONG_PAGE_BACKUP',
    SET_SONG_PAGE_BACKUP_SONG: 'SET_SONG_PAGE_BACKUP_SONG',
    SET_SONG_LIST_PAGE_BACKUP: 'SET_SONG_LIST_PAGE_BACKUP',
    SET_REPERTORY_PAGE_BACKUP: 'SET_REPERTORY_PAGE_BACKUP',
    SET_REPERTORY_LIST_PAGE_BACKUP: 'SET_REPERTORY_LIST_PAGE_BACKUP',
    SET_LIBRARY_PAGE_BACKUP: 'SET_LIBRARY_PAGE_BACKUP',
}