export const types = {
    SET_ITEM_LIST: 'SET_ITEM_LIST',
    SET_ITEM_LIST_STATUS: 'SET_ITEM_LIST_STATUS',

    SET_ITEM: 'SET_ITEM',
    SET_ITEM_STATUS: 'SET_ITEM_STATUS',

    CREATE_ITEM: 'CREATE_ITEM',
    CREATE_ITEM_STATUS: 'CREATE_ITEM_STATUS',

    EDIT_ITEM: 'EDIT_ITEM',
    EDIT_ITEM_STATUS: 'EDIT_ITEM_STATUS',

    DELETE_ITEM: 'DELETE_ITEM',
    DELETE_ITEM_STATUS: 'DELETE_ITEM_STATUS',
}