export const types = {
    SET_LOADING: 'SET_LOADING',

    SET_SONG_LIST: 'SET_SONG_LIST',
    SET_SONG_LIST_STATUS: 'SET_SONG_LIST_STATUS',

    SET_SONG: 'SET_SONG',
    SET_SONG_STATUS: 'SET_SONG_STATUS',

    CREATE_SONG: 'CREATE_SONG',
    CREATE_SONG_STATUS: 'CREATE_SONG_STATUS',

    EDIT_SONG: 'EDIT_SONG',
    EDIT_SONG_STATUS: 'EDIT_SONG_STATUS',

    DELETE_SONG: 'DELETE_SONG',
    DELETE_SONG_STATUS: 'DELETE_SONG_STATUS',

    SET_VERSION_GROUPS: 'SET_VERSION_GROUPS',
}