export const types = {
    RESET_SONG_STATUS: 'RESET_SONG_STATUS',

    FETCH_SONG_LIST: 'FETCH_SONG_LIST',
    FETCH_SONG_LIST_SUCCESS: 'FETCH_SONG_LIST_SUCCESS',
    FETCH_SONG_LIST_FAILURE: 'FETCH_SONG_LIST_FAILURE',

    FETCH_SONG: 'FETCH_SONG',
    FETCH_SONG_SUCCESS: 'FETCH_SONG_SUCCESS',
    FETCH_SONG_FAILURE: 'FETCH_SONG_FAILURE',

    CREATE_SONG: 'CREATE_SONG',
    CREATE_SONG_SUCCESS: 'CREATE_SONG_SUCCESS',
    CREATE_SONG_FAILURE: 'CREATE_SONG_FAILURE',

    EDIT_SONG: 'EDIT_SONG',
    EDIT_SONG_SUCCESS: 'EDIT_SONG_SUCCESS',
    EDIT_SONG_FAILURE: 'EDIT_SONG_FAILURE',

    DELETE_SONG: 'DELETE_SONG',
    DELETE_SONG_SUCCESS: 'DELETE_SONG_SUCCESS',
    DELETE_SONG_FAILURE: 'DELETE_SONG_FAILURE',


    SET_VERSION_GROUPS: 'SET_VERSION_GROUPS',


    // SET_SONG_LOADING: 'SET_SONG_LOADING',
    // RESET_SONG_STATUS: 'RESET_SONG_STATUS',

    // SET_SONG_LIST: 'SET_SONG_LIST',
    // SET_SONG_LIST_STATUS: 'SET_SONG_LIST_STATUS',

    // SET_SONG: 'SET_SONG',
    // SET_SONG_STATUS: 'SET_SONG_STATUS',

    // CREATE_SONG: 'CREATE_SONG',
    // CREATE_SONG_STATUS: 'CREATE_SONG_STATUS',

    // EDIT_SONG: 'EDIT_SONG',
    // EDIT_SONG_STATUS: 'EDIT_SONG_STATUS',

    // DELETE_SONG: 'DELETE_SONG',
    // DELETE_SONG_STATUS: 'DELETE_SONG_STATUS',

    // SET_VERSION_GROUPS: 'SET_VERSION_GROUPS',
}