export const types = {
    SET_SONG_LIST_STATUS: 'SET_SONG_LIST_STATUS',
    SET_SONG_LIST_USER_ID: 'SET_SONG_LIST_USER_ID',
    RESET_SONG_ACTION_STATUS: 'RESET_SONG_ACTION_STATUS',

    FETCH_SONG_LIST: 'FETCH_SONG_LIST',
    FETCH_SONG_LIST_SUCCESS: 'FETCH_SONG_LIST_SUCCESS',
    FETCH_SONG_LIST_FAILURE: 'FETCH_SONG_LIST_FAILURE',

    FETCH_SONG: 'FETCH_SONG',
    FETCH_SONG_SUCCESS: 'FETCH_SONG_SUCCESS',
    FETCH_SONG_FAILURE: 'FETCH_SONG_FAILURE',

    CREATE_SONG: 'CREATE_SONG',
    CREATE_SONG_SUCCESS: 'CREATE_SONG_SUCCESS',
    CREATE_SONG_FAILURE: 'CREATE_SONG_FAILURE',

    EDIT_SONG: 'EDIT_SONG',
    EDIT_SONG_SUCCESS: 'EDIT_SONG_SUCCESS',
    EDIT_SONG_FAILURE: 'EDIT_SONG_FAILURE',

    PUBLISH_SONG: 'PUBLISH_SONG',
    PUBLISH_SONG_SUCCESS: 'PUBLISH_SONG_SUCCESS',
    PUBLISH_SONG_FAILURE: 'PUBLISH_SONG_FAILURE',

    DELETE_SONG: 'DELETE_SONG',
    DELETE_SONG_SUCCESS: 'DELETE_SONG_SUCCESS',
    DELETE_SONG_FAILURE: 'DELETE_SONG_FAILURE',


    SET_SONG_LIST_PAGE_BACKUP: 'SET_SONG_LIST_PAGE_BACKUP',
}