export const types = {
    SET_USER_LOADING: 'SET_USER_LOADING',

    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',

    SET_DEVICE: 'SET_DEVICE',

    SET_USER_SONG_PAGE_OPTIONS: 'SET_USER_SONG_PAGE_OPTIONS',
}