export const types = {
    SET_REPERTORY_LIST: 'SET_REPERTORY_LIST',
    SET_REPERTORY_LIST_STATUS: 'SET_REPERTORY_LIST_STATUS',

    SET_REPERTORY: 'SET_REPERTORY',
    SET_REPERTORY_STATUS: 'SET_REPERTORY_STATUS',

    CREATE_REPERTORY: 'CREATE_REPERTORY',
    CREATE_REPERTORY_STATUS: 'CREATE_REPERTORY_STATUS',

    EDIT_REPERTORY: 'EDIT_REPERTORY',
    EDIT_REPERTORY_STATUS: 'EDIT_REPERTORY_STATUS',

    DELETE_REPERTORY: 'DELETE_REPERTORY',
    DELETE_REPERTORY_STATUS: 'DELETE_REPERTORY_STATUS',
}