export const types = {
    SET_REPERTORY_LIST_STATUS: 'SET_REPERTORY_LIST_STATUS',
    SET_REPERTORY_LIST_USER_ID: 'SET_REPERTORY_LIST_USER_ID',
    RESET_REPERTORY_ACTION_STATUS: 'RESET_REPERTORY_ACTION_STATUS',

    FETCH_REPERTORY_LIST: 'FETCH_REPERTORY_LIST',
    FETCH_REPERTORY_LIST_SUCCESS: 'FETCH_REPERTORY_LIST_SUCCESS',
    FETCH_REPERTORY_LIST_FAILURE: 'FETCH_REPERTORY_LIST_FAILURE',

    FETCH_REPERTORY: 'FETCH_REPERTORY',
    FETCH_REPERTORY_SUCCESS: 'FETCH_REPERTORY_SUCCESS',
    FETCH_REPERTORY_FAILURE: 'FETCH_REPERTORY_FAILURE',

    CREATE_REPERTORY: 'CREATE_REPERTORY',
    CREATE_REPERTORY_SUCCESS: 'CREATE_REPERTORY_SUCCESS',
    CREATE_REPERTORY_FAILURE: 'CREATE_REPERTORY_FAILURE',

    EDIT_REPERTORY: 'EDIT_REPERTORY',
    EDIT_REPERTORY_SUCCESS: 'EDIT_REPERTORY_SUCCESS',
    EDIT_REPERTORY_FAILURE: 'EDIT_REPERTORY_FAILURE',

    PUBLISH_REPERTORY: 'PUBLISH_REPERTORY',
    PUBLISH_REPERTORY_SUCCESS: 'PUBLISH_REPERTORY_SUCCESS',
    PUBLISH_REPERTORY_FAILURE: 'PUBLISH_REPERTORY_FAILURE',

    DELETE_REPERTORY: 'DELETE_REPERTORY',
    DELETE_REPERTORY_SUCCESS: 'DELETE_REPERTORY_SUCCESS',
    DELETE_REPERTORY_FAILURE: 'DELETE_REPERTORY_FAILURE',
}